# Generated by Django 6.0.3 on 2026-04-07 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_userprofile_and_auth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, db_column='MaMon', max_length=50, null=True, verbose_name='Mã môn'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_url',
            field=models.URLField(db_column='UrlKhoaHoc', unique=True, verbose_name='Link khóa học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='NgayTao', verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(db_column='MaKhoaHoc', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(db_column='TrangThai', default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='course',
            name='normalized_title',
            field=models.CharField(blank=True, db_column='TieuDeChuanHoa', max_length=255, verbose_name='Tên khóa học đã chuẩn hóa'),
        ),
        migrations.AlterField(
            model_name='course',
            name='provider',
            field=models.CharField(db_column='DonViToChuc', max_length=120, verbose_name='Tổ chức'),
        ),
        migrations.AlterField(
            model_name='course',
            name='search_document',
            field=models.TextField(blank=True, db_column='VanBanTimKiem', verbose_name='Văn bản tìm kiếm'),
        ),
        migrations.AlterField(
            model_name='course',
            name='source_row',
            field=models.PositiveIntegerField(blank=True, db_column='DongNguon', null=True, verbose_name='Dòng nguồn'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tokenized_text',
            field=models.TextField(blank=True, db_column='TokenDaXuLy', verbose_name='Tokens đã xử lý'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='NgayCapNhat', verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='NgayTao', verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(db_column='MaHoSo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, db_column='LinhVucQuanTam', verbose_name='Lĩnh vực quan tâm'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='learning_goal',
            field=models.TextField(blank=True, db_column='MucTieuHocTap', verbose_name='Mục tiêu học tập'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='learning_needs',
            field=models.TextField(blank=True, db_column='NhuCauHocTap', verbose_name='Nhu cầu học tập'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(db_column='DaHoanThanhOnboarding', default=False, verbose_name='Đã hoàn thành onboarding'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_column='TrinhDo', max_length=20, verbose_name='Trình độ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='NgayCapNhat', verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(db_column='MaNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterModelTable(
            name='course',
            table='KhoaHoc',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='HoSoNguoiHoc',
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(db_column='MaLichSu', primary_key=True, serialize=False)),
                ('query_text', models.CharField(db_column='TuKhoaTimKiem', max_length=500, verbose_name='Từ khóa tìm kiếm')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ThoiDiemTimKiem', verbose_name='Thời điểm tìm kiếm')),
                ('user', models.ForeignKey(db_column='MaNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lịch sử tìm kiếm',
                'verbose_name_plural': 'Lịch sử tìm kiếm',
                'db_table': 'LichSuTimKiem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedCourse',
            fields=[
                ('id', models.BigAutoField(db_column='MaLuu', primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True, db_column='NgayLuu', verbose_name='Ngày lưu')),
                ('course', models.ForeignKey(db_column='MaKhoaHoc', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='api.course', verbose_name='Khóa học')),
                ('user', models.ForeignKey(db_column='MaNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='saved_courses', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Khóa học đã lưu',
                'verbose_name_plural': 'Khóa học đã lưu',
                'db_table': 'KhoaHocDaLuu',
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='UQ_KhoaHocDaLuu_MaNguoiDung_MaKhoaHoc')],
            },
        ),
    ]
