# Generated by Django 6.0.3 on 2026-04-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_course_code_alter_course_course_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_column='TieuDe', max_length=255, verbose_name='Tên khóa học'),
        ),
    ]
