# Generated by Django 6.0.3 on 2026-04-07 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_course_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_type',
            field=models.CharField(blank=True, db_column='LoaiChungChi', max_length=50, verbose_name='Loại chứng chỉ'),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(blank=True, db_column='DoKho', max_length=20, verbose_name='Độ khó'),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_hours',
            field=models.PositiveIntegerField(blank=True, db_column='SoGio', null=True, verbose_name='Số giờ ước tính'),
        ),
        migrations.AddField(
            model_name='course',
            name='price_type',
            field=models.CharField(db_column='LoaiGia', default='free', max_length=20, verbose_name='Loại giá'),
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(db_column='MaLoTrinh', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='TieuDe', max_length=255, verbose_name='Tiêu đề lộ trình')),
                ('input_text', models.TextField(db_column='VanBanDauVao', verbose_name='Văn bản đầu vào')),
                ('target_role', models.CharField(blank=True, db_column='ViTriMucTieu', max_length=255, verbose_name='Vị trí mục tiêu')),
                ('extracted_skills', models.TextField(blank=True, db_column='KyNangTrichXuat', verbose_name='Kỹ năng trích xuất (JSON)')),
                ('roadmap_data', models.TextField(blank=True, db_column='DuLieuLoTrinh', verbose_name='Dữ liệu lộ trình (JSON)')),
                ('is_active', models.BooleanField(db_column='TrangThai', default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='NgayTao', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='NgayCapNhat', verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(db_column='MaNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lộ trình học tập',
                'verbose_name_plural': 'Lộ trình học tập',
                'db_table': 'LoTrinh',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(db_column='MaBuoc', primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_column='ThuTu', verbose_name='Thứ tự')),
                ('phase_name', models.CharField(db_column='TenGiaiDoan', max_length=255, verbose_name='Tên giai đoạn')),
                ('description', models.TextField(blank=True, db_column='MoTa', verbose_name='Mô tả')),
                ('skills', models.TextField(blank=True, db_column='KyNang', verbose_name='Kỹ năng (JSON)')),
                ('is_completed', models.BooleanField(db_column='DaHoanThanh', default=False, verbose_name='Đã hoàn thành')),
                ('course', models.ForeignKey(blank=True, db_column='MaKhoaHoc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_steps', to='api.course', verbose_name='Khóa học gợi ý')),
                ('roadmap', models.ForeignKey(db_column='MaLoTrinh', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.roadmap', verbose_name='Lộ trình')),
            ],
            options={
                'verbose_name': 'Bước lộ trình',
                'verbose_name_plural': 'Bước lộ trình',
                'db_table': 'BuocLoTrinh',
                'ordering': ['order'],
            },
        ),
    ]
