# Generated by Django 6.0.3 on 2026-04-07 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course_certificate_type_course_difficulty_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(db_column='MaDanhGia', primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(db_column='DiemDanhGia', verbose_name='Điểm đánh giá (1-5)')),
                ('comment', models.TextField(blank=True, db_column='NhanXet', verbose_name='Nhận xét')),
                ('is_active', models.BooleanField(db_column='TrangThai', default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='NgayTao', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='NgayCapNhat', verbose_name='Ngày cập nhật')),
                ('course', models.ForeignKey(db_column='MaKhoaHoc', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.course', verbose_name='Khóa học')),
                ('user', models.ForeignKey(db_column='MaNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name': 'Đánh giá khóa học',
                'verbose_name_plural': 'Đánh giá khóa học',
                'db_table': 'DanhGiaKhoaHoc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(db_column='MaVote', primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], db_column='LoaiVote', max_length=4, verbose_name='Loại vote')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='NgayTao', verbose_name='Ngày tạo')),
                ('review', models.ForeignKey(db_column='MaDanhGia', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.coursereview', verbose_name='Đánh giá')),
                ('user', models.ForeignKey(db_column='MaNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL, verbose_name='Người vote')),
            ],
            options={
                'verbose_name': 'Vote đánh giá',
                'verbose_name_plural': 'Vote đánh giá',
                'db_table': 'VoteDanhGia',
            },
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='UQ_DanhGia_MaNguoiDung_MaKhoaHoc'),
        ),
        migrations.AddConstraint(
            model_name='reviewvote',
            constraint=models.UniqueConstraint(fields=('user', 'review'), name='UQ_Vote_MaNguoiDung_MaDanhGia'),
        ),
    ]
