# Generated by Django 6.0.3 on 2026-04-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_coursereview_reviewvote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(db_column='MaDanhMuc', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='TenDanhMuc', max_length=120, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(db_column='Slug', max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, db_column='MoTa', verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='NgayTao', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='NgayCapNhat', verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Danh mục khóa học',
                'verbose_name_plural': 'Danh mục khóa học',
                'db_table': 'DanhMucKhoaHoc',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.BigAutoField(db_column='MaTag', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='TenTag', max_length=120, unique=True, verbose_name='Tên tag')),
                ('slug', models.SlugField(db_column='Slug', max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, db_column='MoTa', verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='NgayTao', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='NgayCapNhat', verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Tag khóa học',
                'verbose_name_plural': 'Tag khóa học',
                'db_table': 'TagKhoaHoc',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, db_column='MaDanhMuc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='api.coursecategory', verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='KhoaHoc_Tag', related_name='courses', to='api.coursetag', verbose_name='Tags'),
        ),
    ]
