# Generated by Django 6.0.3 on 2026-05-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_coursecategory_coursetag_course_category_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, db_column='AnhDaiDien', null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
    ]
