# Generated by Django 6.0.3 on 2026-05-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='MaDanhMucCha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.coursecategory', verbose_name='Danh mục cha'),
        ),
    ]
