# Generated by Django 6.0.3 on 2026-05-10 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_coursecategory_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(db_column='MaLog', primary_key=True, serialize=False)),
                ('context', models.CharField(choices=[('dashboard', 'Dashboard'), ('search', 'Tìm kiếm')], db_column='NguCanh', max_length=20, verbose_name='Ngữ cảnh')),
                ('query_text', models.TextField(blank=True, db_column='VanBanTruyVan', verbose_name='Văn bản truy vấn')),
                ('recommended_course_ids', models.TextField(db_column='DanhSachMaKhoaHoc', help_text='JSON array of course IDs', verbose_name='Danh sách ID khóa học gợi ý (JSON)')),
                ('score_avg', models.FloatField(blank=True, db_column='DiemTrungBinh', null=True, verbose_name='Điểm tin cậy trung bình')),
                ('result_count', models.IntegerField(db_column='SoKetQua', default=0, verbose_name='Số kết quả')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='NgayTao', verbose_name='Thời gian')),
                ('user', models.ForeignKey(db_column='MaNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Log gợi ý AI',
                'verbose_name_plural': 'Log gợi ý AI',
                'db_table': 'LogGoiY',
                'ordering': ['-created_at'],
            },
        ),
    ]
