# Generated by Django 6.0.3 on 2026-05-14 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_recommendation_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(db_column='MaBaiViet', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='TieuDe', max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(db_column='NoiDung', verbose_name='Nội dung')),
                ('is_active', models.BooleanField(db_column='TrangThai', default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='NgayTao', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='NgayCapNhat', verbose_name='Ngày cập nhật')),
                ('course', models.ForeignKey(blank=True, db_column='MaKhoaHoc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='api.course', verbose_name='Khóa học (tùy chọn)')),
                ('user', models.ForeignKey(db_column='MaNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL, verbose_name='Người đăng')),
            ],
            options={
                'verbose_name': 'Bài viết cộng đồng',
                'verbose_name_plural': 'Bài viết cộng đồng',
                'db_table': 'BaiVietCongDong',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(db_column='MaVoteBaiViet', primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], db_column='LoaiVote', max_length=4, verbose_name='Loại vote')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='NgayTao', verbose_name='Ngày tạo')),
                ('post', models.ForeignKey(db_column='MaBaiViet', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.communitypost', verbose_name='Bài viết')),
                ('user', models.ForeignKey(db_column='MaNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to=settings.AUTH_USER_MODEL, verbose_name='Người vote')),
            ],
            options={
                'verbose_name': 'Vote bài viết',
                'verbose_name_plural': 'Vote bài viết',
                'db_table': 'VoteBaiViet',
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='UQ_Vote_MaNguoiDung_MaBaiViet')],
            },
        ),
    ]
