# Generated by Django 6.0.3 on 2026-05-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_communitypost_postvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, db_column='AnhBaiViet', null=True, upload_to='posts/', verbose_name='Ảnh bài viết'),
        ),
    ]
