from django.urls import path, re_path

from .admin_views import (
    AdminCategoryAPIView,
    AdminCourseAPIView,
    AdminStatsAPIView,
    AdminTagAPIView,
    AdminUserListAPIView,
)
from .views import (
    CompareCoursesAPIView,
    CourseDetailAPIView,
    CourseListAPIView,
    DashboardStatsAPIView,
    EduPathTokenObtainPairView,
    GenerateRoadmapAPIView,
    HelloWorldAPIView,
    MeAPIView,
    OnboardingAPIView,
    RecommendationAPIView,
    RefreshTokenAPIView,
    RegisterAPIView,
    ReviewListCreateAPIView,
    ReviewVoteAPIView,
    RoadmapDetailAPIView,
    RoadmapListAPIView,
    SavedCourseAPIView,
    SavedCourseDetailAPIView,
    SearchAPIView,
    SearchHistoryAPIView,
    SearchHistoryDetailAPIView,
)

urlpatterns = [
    path("hello/", HelloWorldAPIView.as_view(), name="hello_world"),
    re_path(r"^hello$", HelloWorldAPIView.as_view()),
    path("courses/", CourseListAPIView.as_view(), name="course_list"),
    re_path(r"^courses$", CourseListAPIView.as_view()),
    path("courses/<int:course_id>/", CourseDetailAPIView.as_view(), name="course_detail"),
    re_path(r"^courses/(?P<course_id>\d+)$", CourseDetailAPIView.as_view()),
    # Course comparison
    path("courses/compare/", CompareCoursesAPIView.as_view(), name="compare_courses"),
    re_path(r"^courses/compare$", CompareCoursesAPIView.as_view()),
    path("auth/register/", RegisterAPIView.as_view(), name="register"),
    re_path(r"^auth/register$", RegisterAPIView.as_view()),
    path("auth/login/", EduPathTokenObtainPairView.as_view(), name="login"),
    re_path(r"^auth/login$", EduPathTokenObtainPairView.as_view()),
    path("auth/refresh/", RefreshTokenAPIView.as_view(), name="token_refresh"),
    re_path(r"^auth/refresh$", RefreshTokenAPIView.as_view()),
    path("auth/me/", MeAPIView.as_view(), name="me"),
    re_path(r"^auth/me$", MeAPIView.as_view()),
    path("auth/onboarding/", OnboardingAPIView.as_view(), name="onboarding"),
    re_path(r"^auth/onboarding$", OnboardingAPIView.as_view()),
    path("recommendations/", RecommendationAPIView.as_view(), name="recommendations"),
    re_path(r"^recommendations$", RecommendationAPIView.as_view()),
    path("search/", SearchAPIView.as_view(), name="search"),
    re_path(r"^search$", SearchAPIView.as_view()),
    path("search/history/", SearchHistoryAPIView.as_view(), name="search_history"),
    re_path(r"^search/history$", SearchHistoryAPIView.as_view()),
    path("search/history/<int:history_id>/", SearchHistoryDetailAPIView.as_view(), name="search_history_detail"),
    re_path(r"^search/history/(?P<history_id>\d+)$", SearchHistoryDetailAPIView.as_view()),
    path("saved-courses/", SavedCourseAPIView.as_view(), name="saved_courses"),
    re_path(r"^saved-courses$", SavedCourseAPIView.as_view()),
    path("saved-courses/<int:course_id>/", SavedCourseDetailAPIView.as_view(), name="saved_course_detail"),
    re_path(r"^saved-courses/(?P<course_id>\d+)$", SavedCourseDetailAPIView.as_view()),
    # Roadmap endpoints
    path("roadmap/generate/", GenerateRoadmapAPIView.as_view(), name="generate_roadmap"),
    re_path(r"^roadmap/generate$", GenerateRoadmapAPIView.as_view()),
    path("roadmaps/", RoadmapListAPIView.as_view(), name="roadmap_list"),
    re_path(r"^roadmaps$", RoadmapListAPIView.as_view()),
    path("roadmaps/<int:roadmap_id>/", RoadmapDetailAPIView.as_view(), name="roadmap_detail"),
    re_path(r"^roadmaps/(?P<roadmap_id>\d+)$", RoadmapDetailAPIView.as_view()),
    # Dashboard stats
    path("dashboard/stats/", DashboardStatsAPIView.as_view(), name="dashboard_stats"),
    re_path(r"^dashboard/stats$", DashboardStatsAPIView.as_view()),
    # Reviews
    path("reviews/", ReviewListCreateAPIView.as_view(), name="reviews"),
    re_path(r"^reviews$", ReviewListCreateAPIView.as_view()),
    path("reviews/<int:review_id>/vote/", ReviewVoteAPIView.as_view(), name="review_vote"),
    re_path(r"^reviews/(?P<review_id>\d+)/vote$", ReviewVoteAPIView.as_view()),
    # Admin-only endpoints
    path("admin/stats/", AdminStatsAPIView.as_view(), name="admin_stats"),
    re_path(r"^admin/stats$", AdminStatsAPIView.as_view()),
    path("admin/users/", AdminUserListAPIView.as_view(), name="admin_users"),
    re_path(r"^admin/users$", AdminUserListAPIView.as_view()),
    path("admin/courses/", AdminCourseAPIView.as_view(), name="admin_courses"),
    re_path(r"^admin/courses$", AdminCourseAPIView.as_view()),
    path("admin/categories/", AdminCategoryAPIView.as_view(), name="admin_categories"),
    re_path(r"^admin/categories$", AdminCategoryAPIView.as_view()),
    path("admin/tags/", AdminTagAPIView.as_view(), name="admin_tags"),
    re_path(r"^admin/tags$", AdminTagAPIView.as_view()),
]
