export { DashboardPage } from './DashboardPage'
export { SearchPage } from './SearchPage'
export { RoadmapPage } from './RoadmapPage'
export { StudentHubPage } from './StudentHubPage'
export { SavedCoursesPage } from './SavedCoursesPage'
export { SearchHistoryPage } from './SearchHistoryPage'
export { ProfilePage } from './ProfilePage'
export { CourseDetailPage } from './CourseDetailPage'
